PeerOrgs:
  - Name: FleetManager
    Domain: fleetmanager.demo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: RepairShop
    Domain: repairshop.demo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: InsuranceProvider
    Domain: insuranceprovider.demo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Vehicles
    Domain: vehicles.demo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

OrdererOrgs:
  - Name: Orderer
    Domain: orderer.demo.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer