---
Organizations:
  - &demo-com
      Name: demo-com
      ID: demo-com
      MSPDir: keyfiles/ordererOrganizations/demo.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('demo-com.member')"
        Writers:
          Type: Signature
          Rule: "OR('demo-com.member')"
        Admins:
          Type: Signature
          Rule: "OR('demo-com.admin')"
  - &org0-com
      Name: org0-com
      ID: org0-com
      MSPDir: keyfiles/peerOrganizations/org0.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('org0-com.admin', 'org0-com.peer', 'org0-com.client')"
        Writers:
          Type: Signature
          Rule: "OR('org0-com.admin', 'org0-com.client')"
        Admins:
          Type: Signature
          Rule: "OR('org0-com.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('org0-com.peer')"

      AnchorPeers:
      - Host: 10.255.255.254
        Port: 7101
      - Host: 10.255.255.254
        Port: 7102
      - Host: 10.255.255.254
        Port: 7103
      - Host: 10.255.255.254
        Port: 7104

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Addresses:
  - 10.255.255.254:7109
  EtcdRaft:
    Consenters:
    - Host: 10.255.255.254
      Port: 7109
      ClientTLSCert: keyfiles/ordererOrganizations/demo.com/orderers/orderer.demo.com/tls/server.crt
      ServerTLSCert: keyfiles/ordererOrganizations/demo.com/orderers/orderer.demo.com/tls/server.crt
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrgChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *org0-com
      Capabilities:
        <<: *ApplicationCapabilities

  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *demo-com
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - <<: *demo-com
    Consortiums:
      SampleConsortium:
        Organizations:
        - *org0-com
